services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DEBUG: "True"  # Cambiado a mapeo
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: football_db
      POSTGRES_USER: gustavog.spate
      POSTGRES_PASSWORD: panCONqueso123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mqtt-subscriber:
    build:
      context: ./sub/mqtt_sub/info  # Cambiado a la carpeta donde está el Dockerfile del MQTT subscriber
      dockerfile: Dockerfile
    environment:
      MQTT_BROKER_URL: "broker.iic2173.org"  # Cambiado a mapeo
      MQTT_BROKER_PORT: "9000"  # Cambiado a mapeo
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: