services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: football_db
      POSTGRES_USER: gustavog.spate
      POSTGRES_PASSWORD: panCONqueso123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: