# Generated by Django 5.1.1 on 2024-09-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixture_id', models.IntegerField(unique=True)),
                ('referee', models.CharField(blank=True, max_length=100, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('timestamp', models.IntegerField()),
                ('status_long', models.CharField(blank=True, max_length=50, null=True)),
                ('status_short', models.CharField(blank=True, max_length=50, null=True)),
                ('status_elapsed', models.IntegerField(blank=True, null=True)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('league_name', models.CharField(blank=True, max_length=100, null=True)),
                ('league_country', models.CharField(blank=True, max_length=100, null=True)),
                ('league_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('league_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('league_season', models.IntegerField(blank=True, null=True)),
                ('league_round', models.CharField(blank=True, max_length=100, null=True)),
                ('home_team_id', models.IntegerField(blank=True, null=True)),
                ('home_team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('home_team_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('home_team_winner', models.BooleanField(blank=True, null=True)),
                ('away_team_id', models.IntegerField(blank=True, null=True)),
                ('away_team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('away_team_logo', models.CharField(blank=True, max_length=255, null=True)),
                ('away_team_winner', models.BooleanField(blank=True, null=True)),
                ('home_goals', models.IntegerField(blank=True, null=True)),
                ('away_goals', models.IntegerField(blank=True, null=True)),
                ('odds_id', models.IntegerField(blank=True, null=True)),
                ('odds_name', models.CharField(blank=True, max_length=100, null=True)),
                ('odds_home_value', models.FloatField(blank=True, null=True)),
                ('odds_draw_value', models.FloatField(blank=True, null=True)),
                ('odds_away_value', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
