# Generated by Django 4.2 on 2024-10-01 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixtures', '0002_fixture_available_bonuses_bonusrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='available_bonuses',
            field=models.IntegerField(default=40),
        ),
    ]
