version: '3.8'

services:
  postgres:
      image: postgres:14
      container_name: postgres
      environment:
        POSTGRES_USER: gustavog.spate
        POSTGRES_PASSWORD: panCONqueso123?
        POSTGRES_DB: football_db
      ports:
      - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - app-network
        
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://gustavog.spate:your_password@postgres:5432/football_db
    depends_on:
      - mqtt-suscriber
    networks:
      - app-network

  mqtt-suscriber:
    build:
      context: ./mqtt_suscriber
      dockerfile: Dockerfile
    environment:
      - MQTT_BROKER_URL=broker.iic2173.org
      - MQTT_BROKER_PORT=9000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
