name: CI Backend Linter

# Se activará en cada push a la rama main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuración de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Especifica la versión de Python según tu proyecto

      # 3. Instalación de dependencias
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r proyecto_arqui/ApiBackDjango/requirements.txt

    # 4. Ejecución del linter
      - name: Run flake8 linter
        run: |
          source venv/bin/activate
          flake8 proyecto_arqui/ApiBackDjango --count --select=E9,F63,F7,F82 --show-source --statistics

